sudo: required

language: generic

# Specify python for lgtm
python:
- "2.7"

services:
- docker

os:
- linux

before_install:
- docker pull hawcobservatory/hawcbuild:c-6scl

script:
- pwd
- which cmake
- echo $TRAVIS_BUILD_DIR
- docker run -v "${TRAVIS_BUILD_DIR}:/hello-there" hawcobservatory/hawcbuild:c-6scl /bin/bash -c "cd /hello-there && ls -l && cmake . && make && make test" 
