sudo: required

language: generic

services:
- docker

os:
- linux

before_install:
- docker pull hawcobservatory/hawcbuild:c-6

script:
- pwd
- which make
- docker run hawcobservatory/hawcbuild:c-6 /bin/bash -c "which bash" 
