sudo: required

language: generic

services:
- docker

os:
- linux

before_install:
- docker pull hawcobservatory/hawcbuild:c-6

script:
- pwd
- which cmake
- echo $TRAVIS_BUILD_DIR
- docker run hawcobservatory/hawcbuild:c-6 /bin/bash -c "which xcdf" 
#              -e TRAVIS_BUILD_DIR \
#              -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" \
