sudo: required

language: generic

services:
- docker

os:
- linux

before_install:
- docker pull hawcobservatory/hawcbuild:c-6

script:
- pwd
- which cmake
- docker run hawcobservatory/hawcbuild:c-6 \
             -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} \
             /bin/bash -c "ls ${TRAVIS_BUILD_DIR}; which xcdf" 
