version: 2
jobs:
  build:
    docker:
      - image: hawcobservatory/hawcbuild:c-6scl
    steps:
      - run:
          name: Which Git?
          command: 'git --version && which git'
      - checkout
#       - run:
#           name: Installing SUDO
#           command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
#       - run:
#           name: Installing GCC
#           command: 'apt-get update && apt-get install -y gcc g++'
#       - run:
#           name: Install CMAKE
#           command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Compile 0
          command: cmake .
      - run:
          name: Compile 1
          command: make
      - run:
          name: Say hi
          command: ./hello
