version: 2
jobs:
  build:
    docker:
      - image: hawcobservatory/hawcbuild:c-6scl
        environment:
          PATH: "/opt/rh/rh-git29/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        entrypoint: /entrypoint.sh
        command: /bin/bash
    steps:
      - run:
          name: Which Git?
          command: |
            git --version
            which git
      - run:
          name: Environment?
          command: env
      - checkout
      - run:
          name: Get some info...
          command: |
            pwd
            env | sort
            ls -al
            cd build
            ls -al
            ps auxwww
      - run:
          name: CMake
          command: |
            cd /root/project/build
            cmake .
      - run:
          name: Make
          command: |
            cd /root/project/build
            make -j3
      - run:
          name: Tests
          command: |
            cd /root/project/build
            make test
