version: 2
jobs:
  build:
    docker:
      - image: hawcobservatory/hawcbuild:c-6scl
        environment:
          PATH: "/opt/rh/rh-git29/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        entrypoint: /entrypoint.sh
        command: /bin/bash
    steps:
      - run:
          name: Which Git?
          command: |
            git --version
            which git
      - run:
          name: Environment?
          command: env
      - checkout
      - run:
          name: Get some info...
          command: |
            pwd
            env | sort
            ls -al
      - run:
          name: CMake
          command: |
            cd /root/project
            cmake . -DCMAKE_BUILD_TYPE=DEBUG
      - run:
          name: Make
          command: |
            cd /root/project
            make -j3
      - run:
          name: Tests and coverage
          command: |
            cd /root/project
            make test
            pip install pyyaml cpp-coveralls
            coveralls --exclude src/hello.cpp --exclude src/test --gcov-options '\-lp'
            pip install codecov
            export CODECOV_TOKEN="dc9d0a0d-f97f-4256-888e-c32cca547bca"
            . get_code_cov.sh
            codecov
